version: "3.9"

services:
  backend:
    build: ./backend
    container_name: crash_backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: crash_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
